[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.mysqli", "php83Extensions.curl", "php83Extensions.openssl"]

[phases.build]
cmds = ["mkdir -p /app/storage/uploads"]

[start]
cmd = "php -d upload_max_filesize=250M -d post_max_size=260M -d memory_limit=512M -S 0.0.0.0:8080 -t public"
